[project]
name = "mcp-server-example"
version = "0.1.0"
description = "Example server for mcp"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "httpx>=0.28.1",
    "mcp[cli]>=1.6.0",
]
